### ISSUE TITLE
wrong schedulingThroughput in density test

### ISSUE THREAD

**Issue by xial-thu** [kubernetes/perf-tests#1083]
/kind bug
/area clusterloader

When calculating scheduling throughput in density test, I found the calculation is incorrect when running a small test of 300 saturation pods on 16 nodes. The log shows

> I0227 17:38:29.247294 2069840 scheduling_throughput.go:103] SchedulingThroughput: starting collecting throughput data
I0227 17:38:34.247614 2069840 scheduling_throughput.go:118] SchedulingThroughput: labelSelector(group = saturation): 15 pods scheduled
I0227 17:38:39.247969 2069840 scheduling_throughput.go:118] SchedulingThroughput: labelSelector(group = saturation): 127 pods scheduled
I0227 17:38:44.248357 2069840 scheduling_throughput.go:118] SchedulingThroughput: labelSelector(group = saturation): 300 pods scheduled
I0227 17:38:49.248779 2069840 scheduling_throughput.go:118] SchedulingThroughput: labelSelector(group = saturation): 300 pods scheduled
I0227 17:38:54.249241 2069840 scheduling_throughput.go:118] SchedulingThroughput: labelSelector(group = saturation): 300 pods scheduled
I0227 17:38:55.132166 2069840 scheduling_throughput.go:131] SchedulingThroughput: gathering data

300 pods are scheduled within 15 seconds but `gather` stage happens after 25 seconds. In .json output, the average throughput is 12, which is exactly **300/25**. But wait, we should exclude data when all pods are scheduled.

```
{
  "average": 12,
  "perc50": 3,
  "perc90": 34.6,
  "perc99": 34.6
}
```

Below is the part of configuration

```yaml
- name: Collecting saturation pod measurements
  measurements:
  - Identifier: WaitForRunningSaturationDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- measurements:
  - Identifier: SaturationPodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
- measurements:
  - Identifier: SchedulingThroughput
    Method: SchedulingThroughput
    Params:
      action: gather
      threshold: {{$SCHEDULER_THROUGHPUT_THRESHOLD}}
```
