### ISSUE TITLE
NodeCounter does not take into account taints and tolerations

### ISSUE THREAD

**Issue by irozzo-1A** [kubernetes/perf-tests#2046]
**What happened**:
I ran the load test `testing/load/config.yaml` with clusterloader2 on a kubemark cluster with a control-plane I created with kubeadm.
```
ENABLE_PROMETHEUS_SERVER=true PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE=gp2 PROMETHEUS_STORAGE_CLASS_PROVISIONER=kubernetes.io/aws-ebs KUBE_SSH_USER=kubernetes KUBE_SSH_KEY_PATH=/Users/iacopo/.ssh/id_rsa ETCD_CERTIFICATE=/etc/kubernetes/pki/etcd/server.crt ETCD_KEY=/etc/kubernetes/pki/etcd/server.key CL2_ENABLE_PVS=false MASTER_IP=172.20.38.87 ./run-e2e.sh --kubeconfig ~/git_clones/kubemark-terraform/deps/kubernetes/test/kubemark/resources/kubeconfig.kubemark --kubemark-root-kubeconfig ~/.kube/config --provider kubemark --testconfig=./testing/load/config.yaml --nodes=100 --v=2 2>&1  | tee cl2.log
```

When daemonsets were deployed, `wait_for_pods` got stuck as the number of expected pods was never reached, because the `NodeCounter` does not take into account the master node taint:

```
  taints:
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io/master
```

**What you expected to happen**:
Taints and tolerations are taken into account to compute the expected number of daemonset pods.

**How to reproduce it (as minimally and precisely as possible)**:
Create a kubemark cluster using kubeadm to provision the control-plane, with the following configuration.
```
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta3
      kubernetesVersion: v1.22.4
      controlPlaneEndpoint: ${elb_hostname}:6443
      apiServer:
        certSANs:
          - "${elb_hostname}"
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      localAPIEndpoint:
        bindPort: 443
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: JoinConfiguration
      controlPlane:
        localAPIEndpoint:
          bindPort: 443
      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
```
Run clusterloader2 with the aforementioned command.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
