### ISSUE TITLE
Prometheus apiserver service monitor should support beartoken file and ca file

### ISSUE THREAD

**Issue by anson627** [kubernetes/perf-tests#2149]
**What would you like to be added**:
```yaml
  - port: apiserver
    scheme: https
    bearerTokenFile: {{$PROMETHEUS_APISERVER_BEARTOKEN_FILE}}
    tlsConfig:
      insecureSkipVerify: true
      caFile: {{$PROMETHEUS_APISERVER_CA_FILE}}
```
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml#L29

**Why is this needed**:
to avoid 401 unauthorized error for apiserver target scraping, we need be able to pass-in bearerTokenFile as in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint and caFile as in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.TLSConfig
