### ISSUE TITLE
use TemplateToObject rather than RawToObject to parse ObjectTemplate

### ISSUE THREAD

**Issue by lzlaa** [kubernetes/perf-tests#2252]
**What would you like to be added**:
 use TemplateToObject rather than RawToObject when parse ObjectTemplate, in order to use powerful go template functionality.
**Why is this needed**:
Sometimes, we need to dynamically construct an ObjectTemplate based on the input, for example:
```yaml
# objectTemplate.yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  template:
    spec:
{{ if ne .nodeSelector "" }}
      nodeSelector:
           {{.nodeSelector}}
{{end}}
```

https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/test/simple_test_executor.go#L306
Due to the multiple uses of RawToObject in the current code to parse ObjectTemplate, we are unable to utilize the ability to use goTemplate in ObjectTemplate.
