### ISSUE TITLE
Add measurement for running commands within in-cluster pods

### ISSUE THREAD

**Issue by marseel** [kubernetes/perf-tests#2262]
**What would you like to be added**:

Measurement that allows scraping pprofs from arbitrary in-cluster pods. This could be implemented as a measurement that allows to run any command within the pod and saves the output of it.

**Why is this needed**:

Currently, we have only measurement that allows us to scrape pprofs from k8s control plane. 
In some cases, we would like to get them for in-cluster running pods. As an example, cilium-agent can affect the PodStartupLatency of pods and such profiles could help us with debugging such issues. 

**Measurement interface**:

Example measurement interface that I have in mind:
```
  - Identifier: PodPeriodicCommand
    Method: PodPeriodicCommand
    Params:
      action: {{$action}} # start/gather 
      labelSelector: app.kubernetes.io/name = cilium-agent
      interval: 5m
      container: cilium-agent
      limit: 3 # randomly picks up to 3 pods that match labelSelector
      commands:
      - name: AllocsProfile
        command: curl -s -k http://localhost:6060/debug/pprof/allocs
        timeout: 5s
      - name: HeapProfile
        command: curl -s -k http://localhost:6060/debug/pprof/heap
        timeout: 5s
     ...
```

**Implementation pointers**:

Related pprof scraping from k8s control plane: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/profile.go

We also have an example of how to run commands within pod: https://github.com/kubernetes/perf-tests/blob/54a3318bf1ad70fdef2c7da6af000aa0c4d00998/clusterloader2/pkg/prometheus/util.go#L159
or this https://github.com/kubernetes/perf-tests/blob/54a3318bf1ad70fdef2c7da6af000aa0c4d00998/clusterloader2/pkg/execservice/exec_service.go#L138
not sure which approach is better, but probably we don't want to use `kubectl` so I would go with the first approach.
