### ISSUE TITLE
Reduce boilerplate around WaitForControlledPodsRunning measurments

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#794]
In load tests there is a lot of boilerplate and code repetition to start and gather WaitForControlledPodsRunning for different kinds of resources (Deployments, StatefulSets, DaemonSets, etc.).
We should create a wrapper measurement that will allow us to express exactly the same in a few lines of code instead. 

/area clusterloader
/good-first-issue

**Comment by vamossagar12** [comment]
hi @mm4tt Is this issue resolved?

**Comment by mm4tt** [comment]
Hey @vamossagar12, no, it's still open :)

**Comment by vamossagar12** [comment]
ok let me assign it to myself. May need your help though :D

**Comment by mm4tt** [comment]
Great! 
I'll update the issue with more concrete description of what has to be done today / tomorrow morning. Thanks! :)

**Comment by mm4tt** [comment]
Hey, sorry for the late reply.

Good way of starting this would be to introduce a new measurement that would allow to call some method on set of other measurements.
An use case for that would be the ["WaitForPodsToBeRunning" step](https://github.com/kubernetes/perf-tests/blob/b34ec893e155e33d69c6d325aa22dd9e36fe2f8d/clusterloader2/testing/load/config.yaml#L322)
Currently it looks like this 
```
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
   - Identifier: WaitForRunningStatefulSets
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WaitForRunningDaemonSets
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WaitForRunningJobs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
```

With the new measurement it could like like this
```
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForPods
    Method: CallMethodOnMeasurments
    Params:
      Identifiers: WaitForRunningDeployments ,WaitForRunningStatefulSets ,WaitForRunningDaemonSets, WaitForRunningJobs
      Method: WaitForControlledPodsRunning
      Params:
        action: gather
```

An example PR that implements a new can be found here - https://github.com/kubernetes/perf-tests/pull/580

In case of any questions / problems just let me know.
